version: "3"

services:
  pitop:
    command: ros2 launch pitop_ros2 pitop_rplidar.launch.py
    container_name: pitop
    build:
      context: .
      dockerfile: Dockerfile
    # Share the X11 socket with the container
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      # Share the lidar USB device with the container
      - /dev/ttyUSB0:/dev/ttyUSB0
    # Use the host network
    network_mode: host
    # Run the container as privileged
    privileged: true
    # Run the container in interactive mode
    stdin_open: true
    tty: true
